### ISSUE TITLE
BigInt browser support

### ISSUE THREAD

**Issue by mirague** [paulmillr/micro-base58#4]
`BigInt` [isn't supported in a lot of browser versions](https://caniuse.com/bigint), would you consider polyfilling it or using another method like https://gist.github.com/diafygi/90a3e80ca1c2793220e5/?

**Comment by paulmillr** [comment]
<img width="298" alt="Screen Shot 2021-04-15 at 10 42 25 PM" src="https://user-images.githubusercontent.com/574696/114928940-dc3a4f00-9e3b-11eb-982e-b25e66303c91.png">

The adoption number is 90% and is growing every day. One year ago Safari didn't support bigints.

No, I won't change it. I develop other cryptographic libraries that use Bigints. Polyfilling bigints take 6 thousand lines of code. I specifically developed the libs to *not* depend on bigints.

**Comment by mirague** [comment]
Thanks for the reply, we've solved it by using our own adaptation without use of `BigInt`.
